name: On Trigger GitHub API

on:
 repository_dispatch:
    types: [triggerAPI]

# on:
#   push:
#     branches:
#     -  main
#   pull_request:


jobs:
  terraformPlan:
    name: 'Trigger Terraform Plan'
    runs-on: ubuntu-latest
    env:
       revision_number: ${{ github.event.client_payload.revision_number }}
    
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Execute Script
      run: |
        repoURL="https://github.com/UttU28/Pipeline_Site.git"
    
        if [ -d "${{ github.workspace }}/Pipeline_Site" ]; then
            echo "Deleting Existing Directory: ${{ github.workspace }}/Pipeline_Site"
            rm -rf "${{ github.workspace }}/Pipeline_Site"
        fi
    
        echo "Cloning Repo: $repoURL into directory: ${{ github.workspace }}"
        git clone "$repoURL"
        ls

    - name: Log in to Azure CLI
      run: |
        az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}" && az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      
        

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan

    - name: Store tfplan in Azure Blob Storage
      run: |
        az storage blob upload --container-name vault --file tfplan --name tfplan --connection-string "${{ secrets.AZURE_STORAGE_ID }}"
    

  # terraformApply:
  #   name: 'Terraform APPLY'
  #   runs-on: ubuntu-latest
  #   needs: [terraformPlan]
  #   environment: testing

  #   defaults:
  #     run:
  #       shell: bash

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3

  #   - name: Setup Terraform
  #     uses: hashicorp/setup-terraform@v1
  #     with:
  #       cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  #   - name: Download tfplan artifact
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: tfplan
  #       path: .

  #   - name: Execute Script
  #     run: |
  #       repoURL="https://github.com/UttU28/Pipeline_Site.git"
    
  #       if [ -d "${{ github.workspace }}/Pipeline_Site" ]; then
  #           echo "Deleting Existing Directory: ${{ github.workspace }}/Pipeline_Site"
  #           rm -rf "${{ github.workspace }}/Pipeline_Site"
  #       fi
    
  #       echo "Cloning Repo: $repoURL into directory: ${{ github.workspace }}"
  #       git clone "$repoURL"

  #   - name: Log in to Azure CLI
  #     run: |
  #       az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}" && az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      
  #   - name: Terraform Init
  #     run: terraform init -input=false

  #   - name: Terraform Apply
  #     run: terraform apply --auto-approve -input=false tfplan
    