name: Destroy Triggered

on:
 repository_dispatch:
    types: [terraformDestroy]

# on:
#   push:
#     branches:
#     -  main
#   pull_request:


jobs:
  terraformDestroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: testing

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Download State Plans
      run: |
        az storage blob download --container-name vault --name terraform.tfstate --file terraform.tfstate --connection-string "${{ secrets.AZURE_STORAGE_ID }}"
        az storage blob download --container-name vault --name destructionPlan --file destructionPlan --connection-string "${{ secrets.AZURE_STORAGE_ID }}"

    - name: Log in to Azure CLI
      run: |
        az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}" && az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      
    - name: Terraform Init
      run: terraform init -input=false

    - name: Terraform Destroy
      run: |
        terraform apply --auto-approve -input=false destructionPlan
    