name: On Trigger GitHub API

on:
 repository_dispatch:
    types: [terraformDestroy]

# on:
#   push:
#     branches:
#     -  main
#   pull_request:


jobs:
  terraformDestroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: testing

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Log in to Azure CLI
      run: |
        az login --service-principal -u "${{ secrets.AZURE_CLIENT_ID }}" -p "${{ secrets.AZURE_CLIENT_SECRET }}" --tenant "${{ secrets.AZURE_TENANT_ID }}" && az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      
    - name: Terraform Init
      run: terraform init -input=false

    - name: Download ZIP & Destroy
      run: |
        az storage blob download --container-name vault --name archive.zip --file archive.zip --connection-string "${{ secrets.AZURE_STORAGE_ID }}"
        unzip -o archive.zip
        if [ $? -eq 0 ]; then
          echo "State File DOewloaded."
          terraform destroy --auto-approve -input=false
        else
          echo "Error: Failed to download tfplan, ABORTING DESTROY"
        fi
    