name: 'Terraform Apply'

on:
  push:
    branches:
    -  main
  pull_request:

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  ROOT_PATH: '${{ github.workspace }}'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Log in to Azure CLI
      run: |
        echo "${{ env.ARM_CLIENT_SECRET }}"
        az login --service-principal -u "${{ env.ARM_CLIENT_ID }}" -p "lnS8Q~CJyyJxsyvRSO-6k2pGo6hVKjy2kyK5bcyU" --tenant "${{ env.ARM_TENANT_ID }}" && az account set --subscription "${{ env.ARM_SUBSCRIPTION_ID }}"
      
    - name: Terraform Apply
      run: terraform apply --auto-approve -input=false
